### ISSUE TITLE
Crash report via Google Play

### ISSUE THREAD

**Issue by ironjan** [ironjan/MensaUPB#122]
I encountered a crash right after starting the app. The crash was also reported by another user.

```
java.lang.IllegalStateException: Fragment MenuListingFragment_{422db5f8} is not currently in the FragmentManager
	at android.support.v4.app.FragmentManagerImpl.saveFragmentInstanceState(FragmentManager.java:687)
	at android.support.v4.app.FragmentStatePagerAdapter.destroyItem(FragmentStatePagerAdapter.java:136)
	at android.support.v4.view.ViewPager.setAdapter(ViewPager.java:418)
	at de.ironjan.mensaupb.menus_ui.Menus.switchAdapterTo(Menus.java:151)
	at de.ironjan.mensaupb.menus_ui.Menus_.access$001(Menus_.java:43)
	at de.ironjan.mensaupb.menus_ui.Menus_$1.run(Menus_.java:178)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5103)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)
```

**Comment by ironjan** [comment]
No further reports were made and this error could not be reproduced.
