### ISSUE TITLE
No suitable HttpMessageConverter found for StwMenu

### ISSUE THREAD

**Issue by ironjan** [ironjan/MensaUPB#99]
The beta branch does not download menus anymore. It fails with the following stack trace.

```
E/MenuSyncAdapter(26386):  Could not extract response: no suitable HttpMessageConverter found for response type [[Lde.ironjan.mensaupb.stw.rest_api.StwMenu;] and content type [text/html]
E/MenuSyncAdapter(26386): org.springframework.web.client.RestClientException: Could not extract response: no suitable HttpMessageConverter found for response type [[Lde.ironjan.mensaupb.stw.rest_api.StwMenu;] and content type [text/html]
E/MenuSyncAdapter(26386): 	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:79)
E/MenuSyncAdapter(26386): 	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:655)
E/MenuSyncAdapter(26386): 	at org.springframework.web.client.RestTemplate$ResponseEntityResponseExtractor.extractData(RestTemplate.java:641)
E/MenuSyncAdapter(26386): 	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:484)
E/MenuSyncAdapter(26386): 	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:447)
E/MenuSyncAdapter(26386): 	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:422)
E/MenuSyncAdapter(26386): 	at de.ironjan.mensaupb.stw.rest_api.StwRest_.getMenus(StwRest_.java:42)
E/MenuSyncAdapter(26386): 	at de.ironjan.mensaupb.stw.rest_api.StwRestWrapper.getMenus(StwRestWrapper.java:32)
E/MenuSyncAdapter(26386): 	at de.ironjan.mensaupb.sync.MenuSyncAdapter.downloadMenus(MenuSyncAdapter.java:160)
E/MenuSyncAdapter(26386): 	at de.ironjan.mensaupb.sync.MenuSyncAdapter.syncMenus(MenuSyncAdapter.java:148)
E/MenuSyncAdapter(26386): 	at de.ironjan.mensaupb.sync.MenuSyncAdapter.tryMenuSync(MenuSyncAdapter.java:135)
E/MenuSyncAdapter(26386): 	at de.ironjan.mensaupb.sync.MenuSyncAdapter.onPerformSync(MenuSyncAdapter.java:108)
E/MenuSyncAdapter(26386): 	at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:254)
```

**Comment by ironjan** [comment]
Could not be reproduced until now.
